% Function OBJECT_DIALOG
% 
% CALLING FUNCTION: callback for obj_button in controller figure and
%                   "objects..." menu choice in options menu of controller figure
% ACTIONS: opens/creates object dialog, where objects to be digitized can
%          be defined/edited
% PARENT PROGRAM: Kine_v2_0
% LAST MODIFIED: February 18, 2004 by gwyneth

function object_dialog

controller = findobj('Tag','controller');
data = guidata(controller);

% Put in right place regardless of screen size
h_root = findobj('type','root');
set(h_root,'Units','Characters')
screen_char = get(h_root,'ScreenSize');

xmax = screen_char(3);
ymax = screen_char(4);

l_obj_fig = 110; % characters
h_obj_fig = 40; % characters

if l_obj_fig > xmax | h_obj_fig > ymax
    warndlg('Your screen resolution is too small, silly!  Some text may not be displayed properly')
    l_obj_fig = xmax;
    h_obj_fig = ymax;
end

x_obj_fig = ((xmax - l_obj_fig)/2);
y_obj_fig = ((ymax - h_obj_fig)/2);

% Make Object Dialog figure
obj_fig = figure(...
    'Tag','obj_fig',...
    'Units','characters',...
    'Position',[x_obj_fig y_obj_fig l_obj_fig h_obj_fig],...
    'Name','Kinematics Objects Dialog',...
    'NumberTitle','off',...
    'MenuBar','none'...
    );

config_text = uicontrol(...
    'Style','text',...
    'Tag','config_text',...
    'Units','characters',...
    'Position',[8 35 15 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'String','Configuration'...
    );

config_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','config_menu',...
    'Units','characters',...
    'Position',[27 35.75 30 1],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'CreateFcn','config_menu_CreateFcn',...
    'Callback','load_object_config'...
    );

save_config_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','save_config_button',...
    'Units','characters',...
    'Position',[72 35 30 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'String','Save Configuration As...',...
    'Callback','save_config'...
    );

obj_list = uicontrol(...
    'Style','listbox',...
    'Tag','obj_list',...
    'Units','characters',...
    'Position',[8 15 94 17],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'CreateFcn','load_object_config'...
    );

order_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','order_button',...
    'Units','characters',...
    'Position',[8 11 19 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','Change Order',...
    'Callback','order_button_callback'...
    );

vis_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','vis_button',...
    'Units','characters',...
    'Position',[8 8.5 19 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','ALL Visible',...
    'Callback','make_all_vis'...
    );

edit_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','edit_button',...
    'Units','characters',...
    'Position',[65 11 18 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','Edit Object...',...
    'Callback','edit_object'...
    );

add_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','add_button',...
    'Units','characters',...
    'Position',[85 8.5 17 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','Add Object',...
    'Callback','edit_object_dialog'...
    );


delete_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','delete_button',...
    'Units','characters',...
    'Position',[85 11 17 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','Delete Object',...
    'Callback','delete_object'...
    );

cancel_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','cancel_button',...
    'Units','characters',...
    'Position',[87 2.5 15 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','Cancel',...
    'Callback','delete(gcf)'...
    );

ok_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','ok_button',...
    'Units','characters',...
    'Position',[70 2.5 15 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','OK',...
    'Callback','obj_ok_callback'...
    );

% Save handles
obj_data = guidata(obj_fig);              % get obj_data already stored in guidata structure
obj_data.handles = guihandles(obj_fig);   % get all handles in current figure and save into data.handles structure (listed by Tag)
guidata(obj_fig,obj_data);                % save data structure into figure data structure using GUIDATA

% If data.config does not already exist (i.e. this is the first time) then
% don't make cancel button visible
if isfield(data,'config') == 0
    set(cancel_button,'Visible','off')
    set(obj_fig,'CloseRequestFcn','obj_ok_callback')
end


