% Function CHOOSE_ADVANCE_OPTION
% 
% CALLING FUNCTION: Callback for Advance menu choice
% ACTIONS: Sets data.advance value through mutually exclusive checkbox
%          interface
% PARENT PROGRAM: Kine_v2_0
% LAST MODIFIED: February 20, 2004 by gwyneth

function choose_advance_option

controller = findobj('Tag','controller');
data = guidata(controller);

% Determine figure size
num_choices = 4;
top_space = 6;
bottom_space = 4;
h_fig = (num_choices * 2.5) + top_space + bottom_space;
vert_spacing = bottom_space:2.5:h_fig;

% Put in right place regardless of screen size
h_root = findobj('type','root');
set(h_root,'Units','Characters')
screen_char = get(h_root,'ScreenSize');

xmax = screen_char(3);
ymax = screen_char(4);

l_fig = 35; % characters

if l_fig > xmax | h_fig > ymax
    warndlg('Your screen resolution is too small, silly!  Some text may not be displayed properly')
    l_fig = xmax;
    h_fig = ymax;
end

x_fig = ((xmax - l_fig)/2);
y_fig = ((ymax - h_fig)/2);

advance_fig = figure(...
    'Tag','advance_fig',...
    'Units','characters',...
    'Position',[x_fig y_fig l_fig h_fig],...
    'Name','Change Advance Method',...
    'NumberTitle','off',...
    'MenuBar','none'...
    );

adv_text = uicontrol(...
    'Style','text',...
    'Tag','adv_text',...
    'Units','characters',...
    'Position',[1 h_fig-top_space 31 5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'String','Choose the order in which Kine will automatically advance through the points to be digitized:'...
    );


for i = 1:num_choices
    
    tag_checkbox = ['adv_checkbox_',num2str(i)];
    checkbox_strings = {'no automatic advance' 'point, object, frame' 'frame, point, object' 'point, frame, object'};
    
    x_pos = 3;
    y_pos = bottom_space + (num_choices-i)*2.5;
    
    h_chekcbox = uicontrol(...
        'Style','checkbox',...
        'Tag',tag_checkbox,...
        'Units','characters',...
        'Position',[x_pos y_pos 30 1.75],...
        'BackgroundColor',data.colors.background,...
        'FontName','Helvetica',...
        'FontUnits','points',...
        'FontSize',10,...
        'FontWeight','normal',...
        'UserData',i,...
        'String',checkbox_strings{i},...
        'Callback','adv_checkbox_callback'...
        );
        
end

ok_edit_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','ok_edit_button',...
    'Units','characters',...
    'Position',[12 .75 10 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','OK',...
    'Callback','adv_ok_callback'...
    );

cancel_edit_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','cancel_edit_button',...
    'Units','characters',...
    'Position',[23 .75 10 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','Cancel',...
    'Callback','delete(gcf)'...
    );

if isfield(data,'advance')
    selected = findobj('Parent', advance_fig, 'UserData', data.advance);
    set(selected,'Value',get(selected,'Max'))
end