% Function ORDER_BUTTON_CALLBACK
% 
% CALLING FUNCTION: Callback for order_button in obj_fig
% ACTIONS: Creates a new window to query the desired order, then calls a
%          function to resort the obj_data.kine field order.
% PARENT PROGRAM: Kine_v2_0
% LAST MODIFIED: February 20, 2004 by gwyneth

function order_button_callback

obj_data = guidata(gcf);

controller = findobj('Tag','controller');
data = guidata(controller);

% Get list of all current objects
objects = fieldnames(obj_data.kine);
num_obj = length(objects);
    if num_obj == 0
        warndlg('There are no objects to order!','No objects found')
        return
    end

% Determine figure size (in characters)
top_space = 0;
bottom_space = 4;
h_fig = (num_obj * 2.5) + top_space + bottom_space;
vert_spacing = bottom_space:2.5:h_fig;

% Put in right place regardless of screen size
h_root = findobj('type','root');
set(h_root,'Units','Characters')
screen_char = get(h_root,'ScreenSize');

xmax = screen_char(3);
ymax = screen_char(4);

l_fig = 35; % characters

if l_fig > xmax | h_fig > ymax
    warndlg('Your screen resolution is too small, silly!  Some text may not be displayed properly')
    l_fig = xmax;
    h_fig = ymax;
end

x_fig = ((xmax - l_fig)/2);
y_fig = ((ymax - h_fig)/2);

order_fig = figure(...
    'Tag','order_fig',...
    'Units','characters',...
    'Position',[x_fig y_fig l_fig h_fig],...
    'Name','Change Order',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'DeleteFcn','set_listbox_string'...
    );

for i = 1:num_obj
    
    edit_tag = ['obj',num2str(i),'_edit'];
    text_tag = ['obj',num2str(i),'_text'];
    
    edit_x_pos = 3;
    text_x_pos = 11;
    
    y_pos = bottom_space + (num_obj-i)*2.5;
    
    h_edit = uicontrol(...
        'Style','edit',...
        'Tag',edit_tag,...
        'Units','characters',...
        'Position',[ edit_x_pos y_pos 5 1.75],...
        'BackgroundColor','white',...
        'FontName','Helvetica',...
        'FontUnits','points',...
        'FontSize',10,...
        'FontWeight','normal',...
        'HorizontalAlignment','right',...
        'String',num2str(i)...
        );
    
    h_text = uicontrol(...
        'Style','text',...
        'Tag',text_tag,...
        'Units','characters',...
        'Position',[text_x_pos y_pos 20 1.5],...
        'BackgroundColor',data.colors.background,...
        'FontName','Helvetica',...
        'FontUnits','points',...
        'FontSize',10,...
        'FontWeight','normal',...
        'HorizontalAlignment','left',...
        'String',objects{i}...
        );
    
end

ok_edit_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','ok_edit_button',...
    'Units','characters',...
    'Position',[12 .75 10 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','OK',...
    'Callback','order_ok_callback'...
    );

cancel_edit_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','cancel_edit_button',...
    'Units','characters',...
    'Position',[23 .75 10 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','Cancel',...
    'Callback','delete(gcf)'...
    );

order_data.handles = guihandles(order_fig);   % get all handles in current figure and save into data.handles structure (listed by Tag)
    order_data.objects = objects;             % Save out fieldnames used to make objects list
guidata(order_fig,order_data);                % save data structure into figure data structure using GUIDATA
