% Function UNSPLINE_GUI
% 
% CALLING FUNCTION: Data menu choice "UNspline"
% ACTIONS: Gets user input for unspline command then runs unspline_data.m
% PARENT PROGRAM: Kine_v2_1
% LAST MODIFIED: Jan 08, 2007 by gwyneth

function unspline_gui

controller = findobj('Tag','controller');
data = guidata(controller);


% Put in right place regardless of screen size
h_root = findobj('type','root');
set(h_root,'Units','Characters')
screen_char = get(h_root,'ScreenSize');

xmax = screen_char(3);
ymax = screen_char(4);

l_fig = 70; % characters
h_fig = 17; % characters

if l_fig > xmax | h_fig > ymax
    warndlg('Your screen resolution is too small, silly!  Some text may not be displayed properly')
    l_fig = xmax;
    h_fig = ymax;
end

x_fig = ((xmax - l_fig)/2);
y_fig = ((ymax - h_fig)/2);

% Make Edit Object Dialog figure
edit_fig = figure(...
    'Tag','unspline_gui',...
    'Units','characters',...
    'Position',[x_fig y_fig l_fig h_fig],...
    'Name','unspline GUI',...
    'NumberTitle','off',...
    'MenuBar','none'...
    );

intro_text = uicontrol(...
    'Style','text',...
    'Tag','intro_text',...
    'Units','characters',...
    'Position',[5 14 60 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','Enter information for UNsplining the data:'...
    );

start_frame_text = uicontrol(...
    'Style','text',...
    'Tag','start_frame_text',...
    'Units','characters',...
    'Position',[10 11 18 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','right',...
    'String','Start Frame:'...
    );

start_frame_edit = uicontrol(...
    'Style','edit',...
    'Tag','start_frame_edit',...
    'Units','characters',...
    'Position',[30 11 20 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left'...
    );

end_frame_text = uicontrol(...
    'Style','text',...
    'Tag','end_frame_text',...
    'Units','characters',...
    'Position',[10 8 18 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','right',...
    'String','End Frame:'...
    );

end_frame_edit = uicontrol(...
    'Style','edit',...
    'Tag','end_frame_edit',...
    'Units','characters',...
    'Position',[30 8 20 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left'...
    );

n_text = uicontrol(...
    'Style','text',...
    'Tag','n_text',...
    'Units','characters',...
    'Position',[4 5 24 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'String','Keep data every N = '...
    );

n_edit = uicontrol(...
    'Style','edit',...
    'Tag','n_edit',...
    'Units','characters',...
    'Position',[30 5 20 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left'...
    );

n2_text = uicontrol(...
    'Style','text',...
    'Tag','n2_text',...
    'Units','characters',...
    'Position',[50 5 23 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'String',' frames.'...
    );

ok_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','ok_button',...
    'Units','characters',...
    'Position',[33 1 15 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','OK',...
    'Callback','unspline_gui_callback'...
    );

cancel_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','cancel_button',...
    'Units','characters',...
    'Position',[50 1 15 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','Cancel',...
    'Callback','delete(gcf)'...
    );

% Now run unspline_data with values from the edit boxes.