% Function EDIT_OBJECT_DIALOG
% 
% CALLING FUNCTION: add_object, also callback for edit_button in obj_fig dialog
% ACTIONS: Creates dialog for editing object properties
% PARENT PROGRAM: Kine_v2_0
% LAST MODIFIED: February 19, 2004 by gwyneth

function edit_object_dialog

controller = findobj('Tag','controller');
data = guidata(controller);
% 
% edit_data.caller = get(gcbo,'Tag');     % Figure out which uicontrol called the Edit Object Dialog, 
%                                         % must be either 'add_button' or 'edit_button'
% if strcmp(edit_data.caller,'add_button')
    ok_button_string = 'Add';
% elseif strcmp(edit_data.caller,'edit_button')
%     ok_button_string = 'OK';
% else
%     ok_button_string = 'Uh-oh!';
% end
                      

num_pts_default = '0';

% Put in right place regardless of screen size
h_root = findobj('type','root');
set(h_root,'Units','Characters')
screen_char = get(h_root,'ScreenSize');

xmax = screen_char(3);
ymax = screen_char(4);

l_fig = 70; % characters
h_fig = 17; % characters

if l_fig > xmax | h_fig > ymax
    warndlg('Your screen resolution is too small, silly!  Some text may not be displayed properly')
    l_fig = xmax;
    h_fig = ymax;
end

x_fig = ((xmax - l_fig)/2);
y_fig = ((ymax - h_fig)/2);

% Make Edit Object Dialog figure
edit_fig = figure(...
    'Tag','edit_fig',...
    'Units','characters',...
    'Position',[x_fig y_fig l_fig h_fig],...
    'Name','Edit Objects Dialog',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'DeleteFcn','set_listbox_string'...
    );

name_text = uicontrol(...
    'Style','text',...
    'Tag','name_text',...
    'Units','characters',...
    'Position',[7 15 18 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','right',...
    'String','Object Name:'...
    );

name_edit = uicontrol(...
    'Style','edit',...
    'Tag','name_edit',...
    'Units','characters',...
    'Position',[27 15 30 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left'...
    );

color_text = uicontrol(...
    'Style','text',...
    'Tag','color_text',...
    'Units','characters',...
    'Position',[15 12 10 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','right',...
    'String','Color:'...
    );

color_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','color_menu',...
    'Units','characters',...
    'Position',[27 12 15 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'String',fieldnames(data.colors)...
    );

vis_box = uicontrol(...
    'Style','checkbox',...
    'Tag','vis_box',...
    'Units','characters',...
    'Position',[47 12 20 1.75],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'String','Visible'...
    );
    set(vis_box,'Value',get(vis_box,'Max'))

type_text = uicontrol(...
    'Style','text',...
    'Tag','type_text',...
    'Units','characters',...
    'Position',[7 9 18 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','right',...
    'String','Object Type:'...
    );

type_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','type_menu',...
    'Units','characters',...
    'Position',[27 9 30 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'String',data.types,...
    'Callback','type_menu_callback'...
    );

num_text = uicontrol(...
    'Style','text',...
    'Tag','num_text',...
    'Units','characters',...
    'Position',[2 6 23 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','right',...
    'String','   Number of points:'...
    );

num_edit = uicontrol(...
    'Style','edit',...
    'Tag','num_edit',...
    'Units','characters',...
    'Position',[27 6 5 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','right',...
    'String',num_pts_default,...
    'Callback','num_edit_callback'...
    );

ok_edit_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','ok_edit_button',...
    'Units','characters',...
    'Position',[33 1 15 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String',ok_button_string,...
    'Callback','edit_ok_callback'...
    );

cancel_edit_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','cancel_edit_button',...
    'Units','characters',...
    'Position',[50 1 15 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','Cancel',...
    'Callback','delete(gcf)'...
    );

edit_data.handles = guihandles(edit_fig);   % get all handles in current figure and save into data.handles structure (listed by Tag)

edit_data.handles.to_move = [num_edit, num_text,...
                             type_menu, type_text,...
                             color_menu, color_text,...
                             name_edit, name_text,...
                             vis_box];
                         
edit_data.handles.to_keep = [num_edit, num_text,...
                             type_menu, type_text,...
                             color_menu, color_text,...
                             name_edit, name_text,...
                             vis_box, ok_edit_button, cancel_edit_button];
                         
guidata(edit_fig,edit_data);                % save data structure into figure data structure using GUIDATA

% If there is a type called 'points', make this the default setting
menu_val = strmatch('points',data.types,'exact');
if isempty(menu_val) == 0
    set(type_menu,'Value',menu_val)
end

% Run the appropriate type_menu_callback script
type_menu_callback
