% TEST function for body-centered view dialog

function bcviewdialogtest

controller = findobj('Tag','controller');
data = guidata(controller);
   

txt_axes = {'x-axis','y-axis','z-axis'};
ok_button_string = 'OK';
num_pts_default = '0';

% Put in right place regardless of screen size
h_root = findobj('type','root');
set(h_root,'Units','Characters')
screen_char = get(h_root,'ScreenSize');

xmax = screen_char(3);
ymax = screen_char(4);

l_fig = 70; % characters
h_fig = 30; % characters

if l_fig > xmax | h_fig > ymax
    warndlg('Your screen resolution is too small, silly!  Some text may not be displayed properly')
    l_fig = xmax;
    h_fig = ymax;
end

x_fig = ((xmax - l_fig)/2);
y_fig = ((ymax - h_fig)/2);

% Make Edit Object Dialog figure
bc_fig = figure(...
    'Tag','bc_fig',...
    'Units','characters',...
    'Position',[x_fig y_fig l_fig h_fig],...
    'Name','Edit Objects Dialog',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'DeleteFcn','set_listbox_string'...
    );

instruct_text = uicontrol(...
    'Style','text',...
    'Tag','instruct_text',...
    'Units','characters',...
    'Position',[4 25 62 3],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'String','Choose two orthogonal axes to define your body-centered view:'...
    );

axis1_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','axis1_menu',...
    'Units','characters',...
    'Position',[4 21 13 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'Value',1,...
    'String',txt_axes...
    );

axis2_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','axis2_menu',...
    'Units','characters',...
    'Position',[4 15 13 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'Value',2,...
    'String',txt_axes...
    );

axis1_text1 = uicontrol(...
    'Style','text',...
    'Tag','axis1_text1',...
    'Units','characters',...
    'Position',[18 21 8 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','right',...
    'String','is from'...
    );

axis1_text2 = uicontrol(...
    'Style','text',...
    'Tag','axis1_text2',...
    'Units','characters',...
    'Position',[18 18 8 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','right',...
    'String','to'...
    );

axis1_obj1_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','axis1_obj1_menu',...
    'Units','characters',...
    'Position',[27 21 18 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'Value',1,...
    'String',fieldnames(data.kine),...
    'Callback','set_bcpoint_menu'...
    );

axis1_obj2_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','axis1_obj2_menu',...
    'Units','characters',...
    'Position',[27 18 18 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'Value',1,...
    'String',fieldnames(data.kine),...
    'Callback','set_bcpoint_menu'...
    );

axis1_point1_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','axis1_point1_menu',...
    'Units','characters',...
    'Position',[46 21 20 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'Value',1,...
    'String',data.kine.(get_string(axis1_obj1_menu)).config.points...
    );

axis1_point2_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','axis1_point2_menu',...
    'Units','characters',...
    'Position',[46 18 20 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'Value',1,...
    'String',data.kine.(get_string(axis1_obj1_menu)).config.points...
    );

axis2_text1 = uicontrol(...
    'Style','text',...
    'Tag','axis2_text1',...
    'Units','characters',...
    'Position',[18 15 8 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','right',...
    'String','is from'...
    );

axis2_text2 = uicontrol(...
    'Style','text',...
    'Tag','axis2_text2',...
    'Units','characters',...
    'Position',[18 12 8 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','right',...
    'String','to'...
    );

axis2_obj1_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','axis2_obj1_menu',...
    'Units','characters',...
    'Position',[27 15 18 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'Value',1,...
    'String',fieldnames(data.kine),...
    'Callback','set_bcpoint_menu'...
    );

axis2_obj2_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','axis2_obj2_menu',...
    'Units','characters',...
    'Position',[27 12 18 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'Value',1,...
    'String',fieldnames(data.kine),...
    'Callback','set_bcpoint_menu'...
    );

axis2_point1_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','axis2_point1_menu',...
    'Units','characters',...
    'Position',[46 15 20 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'Value',1,...
    'String',data.kine.(get_string(axis1_obj1_menu)).config.points...
    );

axis2_point2_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','axis2_point2_menu',...
    'Units','characters',...
    'Position',[46 12 20 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'Value',1,...
    'String',data.kine.(get_string(axis1_obj1_menu)).config.points...
    );

orig_text = uicontrol(...
    'Style','text',...
    'Tag','orig_text',...
    'Units','characters',...
    'Position',[4 8 22 1.5],...
    'BackgroundColor',data.colors.background,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','right',...
    'String','The ORIGIN is at'...
    );

axis3_obj3_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','axis3_obj3_menu',...
    'Units','characters',...
    'Position',[27 8 18 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'Value',1,...
    'String',fieldnames(data.kine),...
    'Callback','set_bcpoint_menu'...
    );

axis3_point3_menu = uicontrol(...
    'Style','popupmenu',...
    'Tag','axis3_point3_menu',...
    'Units','characters',...
    'Position',[46 8 20 1.75],...
    'BackgroundColor','white',...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','left',...
    'Value',1,...
    'String',data.kine.(get_string(axis1_obj1_menu)).config.points...
    );

ok_edit_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','ok_edit_button',...
    'Units','characters',...
    'Position',[33 1 15 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String',ok_button_string,...
    'Callback','bc_ok_callback'...
    );

cancel_edit_button = uicontrol(...
    'Style','pushbutton',...
    'Tag','cancel_edit_button',...
    'Units','characters',...
    'Position',[50 1 15 2],...
    'BackgroundColor',data.colors.gray,...
    'FontName','Helvetica',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'String','Cancel',...
    'Callback','delete(gcf)'...
    );

bc_data.handles = guihandles(bc_fig);   % get all handles in current figure and save into data.handles structure (listed by Tag)

bc_data.handles.to_move = [  axis1_menu, axis1_text1, axis1_text2, axis1_obj1_menu, axis1_obj2_menu,  axis1_point1_menu, axis1_point2_menu,...
                             axis2_menu, axis2_text1, axis2_text2, axis2_obj1_menu, axis2_obj2_menu,  axis2_point1_menu, axis2_point2_menu,...
                             orig_text, axis3_obj3_menu, axis3_point3_menu, instruct_text];
                         
bc_data.handles.to_keep = [  axis1_menu, axis1_text1, axis1_text2, axis1_obj1_menu, axis1_obj2_menu,  axis1_point1_menu, axis1_point2_menu,...
                             axis2_menu, axis2_text1, axis2_text2, axis2_obj1_menu, axis2_obj2_menu,  axis2_point1_menu, axis2_point2_menu,...
                             orig_text, axis3_obj3_menu, axis3_point3_menu, instruct_text,...
                             ok_edit_button, cancel_edit_button];
                         
guidata(bc_fig,bc_data);                % save data structure into figure data structure using GUIDATA


